---
all:
  hosts:
    mail.ovirt.org:
    ovirt-web-builder.osci.io:

  children:
    #phx_zone:
    #  hosts:

    # zone managed by OSAS in the Community Cage project
    osci_zone:
      hosts:
        ovirt-web-builder.osci.io:
        mail.ovirt.org:

    mailing:
      hosts:
        mail.ovirt.org:

    web_builders:
      hosts:
        ovirt-web-builder.osci.io:

