---
all:
  hosts:
    mail.phx.ovirt.org:
    ovirt-web-builder.osci.io:

  children:
    phx_zone:
      hosts:
        mail.phx.ovirt.org:

    # zone managed by OSAS in the Community Cage project
    osci_zone:
      hosts:
        ovirt-web-builder.osci.io:

    mailing:
      hosts:
        mail.phx.ovirt.org:

    web_builders:
      hosts:
        ovirt-web-builder.osci.io:

