---
all:
  hosts:
    mail.ovirt.org:
    monitoring.ovirt.org:
      # TODO: remove when DNS is switched
      ansible_host: 8.43.85.199
    ovirt-web-builder.int.osci.io:
    www.phx.ovirt.org:

  children:
    phx_zone:
     hosts:
       www.phx.ovirt.org:

    # zone managed by OSAS in the Community Cage project
    osci_zone:
      hosts:
        mail.ovirt.org:
        monitoring.ovirt.org:
      children:
        osci_internal_zone:
          hosts:
            ovirt-web-builder.int.osci.io:

    mailing:
      hosts:
        mail.ovirt.org:

    web_builders:
      hosts:
        ovirt-web-builder.int.osci.io:

