---
- src: https://github.com/OSAS/ansible-role-selinux
  name: selinux
- src: https://github.com/OSAS/ansible-role-openssh.git
  name: openssh
- src: https://gitlab.com/osas/ansible-role-entropy.git
  name: entropy
- src: https://gitlab.com/osas/ansible-role-guest_virt_tools.git
  name: guest_virt_tools
- src: https://gitlab.com/osas/ansible-role-memcached.git
  name: memcached
- src: https://gitlab.com/osas/ansible-role-postgresql.git
  name: postgresql
- src: https://gitlab.com/osas/ansible-role-mailman3.git
  name: mailman3
- src: https://gitlab.com/osas/ansible-role-postgrey.git
  name: postgrey
- src: https://gitlab.com/osas/ansible-role-postfix.git
  name: postfix
- src: https://github.com/OSAS/ansible-role-httpd
  name: httpd

