---
# do not merge with next item, since epel need to be installed first
- name: install Epel
  package: pkg=epel-release state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: install base rpms
  package: pkg={{ item }} state=present
  with_items:
  - screen
  - htop
  - iftop
  - iotop
  - strace
  - vim-enhanced
  - tcpdump
  - chrony

- name: Install NTP client
  service: name=chronyd state=running enabled=yes

- name: Test if the host is an AWS instance
  stat: path=/etc/cloud/cloud.cfg.d
  register: cloud_init

- name: Preserver AWS instance hostname
  copy: dest=/etc/cloud/cloud.cfg.d/06_preserve_hostname.cfg src=06_preserve_hostname.cfg
  when: cloud_init.stat.isdir is defined and cloud_init.stat.isdir

- name: install firewalld on centos7
  package: pkg=firewalld state=installed
  when: ansible_distribution == 'Fedora' or ansible_distribution_major_version == '7'

# work around cloud image who disable firewalld
- name: Ensure Firewalld is not disabled
  command: systemctl unmask firewalld
  args:
    removes: /etc/systemd/system/firewalld.service
  when: ansible_distribution == 'Fedora'

- name: Start Firewalld
  service: name=firewalld state=started enabled=yes
  when: ansible_distribution == 'Fedora' or ansible_distribution_major_version == '7'
