---

- name: Load settings based on distribution
  include_vars: "{{ item }}"
  with_first_found:
    - "sys_{{ ansible_distribution }}.yml"
    - "sys_{{ ansible_os_family }}.yml"

# do not merge with next item, since epel need to be installed first
- name: install Epel
  package: pkg=epel-release state=present
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

# cannot use 'yum copr' as yum-plugin-copr is missing on CentOS despite Copr's doc
# also there is no Ansible module for it
- name: setup the OSAS Infra repo
  yum_repository:
    name: osas_infra
    description: Copr repo for OSAS ComInfra Team
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/duck/osas-infra-team-rpm-repo/{{ rpm_repo_component }}/"
    gpgkey: "https://copr-be.cloud.fedoraproject.org/results/duck/osas-infra-team-rpm-repo/pubkey.gpg"
    repo_gpgcheck: False
    gpgcheck: True
    skip_if_unavailable: True
    state: present
    enabled: True
  when: ansible_os_family == 'RedHat'
  notify: Clean YUM Metadata

# after all repos are setup and before installing packages
- meta: flush_handlers

- name: install base rpms
  package: pkg={{ item }} state=present
  with_items:
  - screen
  - htop
  - iftop
  - iotop
  - strace
  - vim-enhanced
  - tcpdump
  - chrony

- name: Install NTP client
  service: name=chronyd state=running enabled=yes

- name: Test if the host is an AWS instance
  stat: path=/etc/cloud/cloud.cfg.d
  register: cloud_init

- name: Preserver AWS instance hostname
  copy: dest=/etc/cloud/cloud.cfg.d/06_preserve_hostname.cfg src=06_preserve_hostname.cfg
  when: cloud_init.stat.isdir is defined and cloud_init.stat.isdir

- name: install firewalld on centos7
  package: pkg=firewalld state=installed
  when: ansible_distribution == 'Fedora' or ansible_distribution_major_version == '7'

# work around cloud image who disable firewalld
- name: Ensure Firewalld is not disabled
  command: systemctl unmask firewalld
  args:
    removes: /etc/systemd/system/firewalld.service
  when: ansible_distribution == 'Fedora'

- name: Start Firewalld
  service: name=firewalld state=started enabled=yes
  when: ansible_distribution == 'Fedora' or ansible_distribution_major_version == '7'
