---
- hosts: all
  roles:
  - base
  - entropy
  - guest_virt_tools
  - selinux
  - openssh

# using phases to ensure handlers are called and deps are really ready
#
# phase 1: Mailman deps
- hosts: mailing
  roles:
  - role: memcached
  - role: postgresql
    backup_databases:
      - mailman
# phase 2: Mailman installation
- hosts: mailing
  roles:
  - role: mailman3
    site_owner_email: "root@ovirt.org"
    site_admins:
      - "duck"
      - "duck-rh"
      - "misc"
      - "eedri"
      - "ederevea"
    from_email: "listmaster@ovirt.org"
    webui_name: "oVirt List Archives"
    webui_basedir: /var/www/mailman
    webui_user: mailman_webui
    domains:
      - lists.ovirt.org
      - mail.phx.ovirt.org
    http_vhost: mail.phx.ovirt.org
    rest_pw: "{{ mailman_rest_pw }}"
    auth: "{{ social_auth }}"
  - role: httpd
    website_domain: mail.phx.ovirt.org
    document_root: /var/www/mailman
    force_tls: True
    use_tls: True
    use_letsencrypt: True
    mail_domain: ovirt.org
    wsgi_script: /var/www/mailman/config/webui.wsgi
    wsgi_user: mailman_webui
    allow_app_signals: True
  - role: postgrey
    whitelist_clients:
      - gerrit.ovirt.org
      - redhat.com
  - role: spamassassin
    service_profile: medium
  - role: sasldb
    user_create: "{{ local_mail_accounts }}"
    db_group: mail
  - role: postfix
    myhostname: "mail.phx.ovirt.org"
    mydestination: 
      - "linode01.ovirt.org"
    mynetworks:
      - 52.6.157.53
      - 54.87.87.13
      - 174.129.122.232
      - 173.255.252.138
      - "[2600:3c01::f03c:91ff:fe93:4b0d]"
      - 107.22.51.207
      - 107.22.108.18
      - 23.22.92.7
    auth: sasldb
    tls_method: manual
    cert_file: /etc/pki/tls/certs/star_ovirt_org.bundle.crt
    key_file: /etc/pki/tls/private/star_ovirt_org.key
    with_postgrey: true
    with_mailman3: true
    with_spamassassin: true
    smtpd_options:
      content_filter: spamfilter
    local_accounts:
      - jira
  - role: dovecot
    with_pop3: true
    ca_file: /etc/pki/tls/certs/star_ovirt_org.ca.crt
    cert_file: /etc/pki/tls/certs/star_ovirt_org.bundle.crt
    key_file: /etc/pki/tls/private/star_ovirt_org.key
    auth: yaml-dict
  tasks:
  - name: install mail main aliases
    copy:
      src: mailing/aliases
      dest: /etc/aliases
    notify: reload mail aliases databases
  - name: install Dovecot users
    copy:
      src: mailing/users/
      dest: /etc/dovecot/users/

