---
- hosts: all
  roles:
  - base
  - guest_virt_tools
  - selinux
  - openssh
  tasks:
  - name: install public certificate files
    copy:
      src: "tls/{{ item }}"
      dest: "/etc/pki/tls/certs/{{ item }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - star_ovirt_org.crt
      - star_ovirt_org.ca.crt
    notify: generate bundle certificate file
  - name: install private certificate files
    copy:
      src: "tls/{{ item }}"
      dest: "/etc/pki/tls/private/{{ item }}"
      owner: root
      group: root
      mode: 0600
    with_items:
      - star_ovirt_org.key
    notify: generate bundle certificate file
  handlers:
  - name: generate bundle certificate file
    shell: "cat /etc/pki/tls/certs/star_ovirt_org.crt /etc/pki/tls/certs/star_ovirt_org.ca.crt >/etc/pki/tls/certs/star_ovirt_org.bundle.crt"

- hosts: mailing
  roles:
  - role: memcached
  - role: postgresql
    backup_databases:
      - mailman
  - role: mailman3
    site_owner_email: "root@ovirt.org"
    from_email: "listmaster@ovirt.org"
    webui_name: "oVirt List Archives"
    webui_basedir: /var/www/mailman
    webui_user: mailman_webui
    domains:
      - lists.ovirt.org
    http_vhost: lists.ovirt.org
    rest_pw: "{{ mailman_rest_pw }}"
    auth: "{{ social_auth }}"
  - role: httpd
    website_domain: lists.ovirt.org
    document_root: /var/www/mailman
    # TODO: generate cert
    #force_tls: True
    #use_tls: True
    wsgi_script: /var/www/mailman/config/webui.wsgi
    wsgi_user: mailman_webui
    allow_app_signals: True
  - role: postgrey
    whitelist_clients:
      - gerrit.ovirt.org
      - redhat.com
  - role: postfix
    myhostname: "lists.ovirt.org"
    mydestination: 
      - "$myhostname"
      - "linode01.ovirt.org"
    mynetworks:
      - 127.0.0.0/8
      - "[::1]/128"
      - 52.6.157.53
      - 54.87.87.13
      - 174.129.122.232
      - 173.255.252.138
      - "[2600:3c01::f03c:91ff:fe93:4b0d]"
      - 107.22.51.207
      - 107.22.108.18
      - 23.22.92.7
    auth: sasldb
    smtpd_recipient_restrictions_custom:
      - "check_policy_service unix:postgrey/socket"
    alias_maps_custom:
      - "hash:/etc/postfix/aliases.local"
    alias_database_custom:
      - "hash:/etc/postfix/aliases.local"
    local_recipient_maps_custom:
      - "hash:/etc/postfix/local_recipient"
      - "hash:/var/lib/mailman3/data/postfix_lmtp"
    transport_maps:
      - "hash:/var/lib/mailman3/data/postfix_lmtp"
    relay_domains:
      - "$mydestination"
      - "hash:/var/lib/mailman3/data/postfix_domains" # in case other domains are added in the future
  tasks:
  - name: install mail main aliases
    copy:
      src: mailing/aliases
      dest: /etc/aliases
    notify: reload mail aliases databases
  - name: install mail specific aliases
    copy:
      src: "mailing/{{ item }}"
      dest: "/etc/postfix/{{ item }}"
    with_items:
      - aliases.local
    notify: reload mail aliases databases
  - name: install mail local recipient list
    copy:
      src: mailing/local_recipient
      dest: /etc/postfix/local_recipient
    notify: reload mail system
  # there is unfortunately no module to handle SASL databases
  # TODO: find a way to manage /etc/sasldb2

