---
- hosts: all
  roles:
  - base
  - selinux
  - openssh

- hosts: mailing
  roles:
  - role: memcached
  - role: postgresql
  - role: mailman3
    mailman_site_owner_email: "root@ovirt.org"
    mailman_site_admin_email: "root@ovirt.org"
    # TODO: USE VAULT!!!
    mailman_site_admin_password: "quack"
    mailman_from_email: "listmaster@ovirt.org"
    mailman_webui_name: "oVirt List Archives"
    mailman_webui_basedir: /var/www/mailman
    mailman_webui_user: mailman_webui
    mailman_domains:
      - lists.ovirt.org
    mailman_http_vhost: lists.ovirt.org
  - role: httpd
    website_domain: lists.ovirt.org
    document_root: /var/www/mailman
    # TODO: generate cert
    #force_tls: True
    #use_tls: True
    wsgi_script: /var/www/mailman/config/webui.wsgi
    wsgi_user: mailman_webui
    allow_app_signals: True

