---
- hosts: all
  roles:
  - base
  - entropy
  - guest_virt_tools
  - selinux
  - openssh
  - admin_ssh_keys
  - unattended_updates
  - chrony
  tags: base

# use inventory_hostname or webui_vhost as hostname for MX and IMAP (TLS SAN OK)
- hosts: mail.ovirt.org
  vars:
    webui_vhost: lists.ovirt.org
  tasks:
  - name: Add swap
    include_role:
      name: swap_file
    vars:
      size: 1G
      path: /var/swap
  - name: Install Mailing-Lists Server
    include_role:
      name: mailing-lists-server
    vars:
      display_name: "oVirt List Archives"
      domain: "{{ ovirt_domain }}"
      admin_users:
        - duck
        - misc
        - eyal
        - ederevea
      mail_aliases:
        # Person who should get root's mail
        root: "{{ ['root'] + ovirt_infra_emails }}"
        listmaster: root
        www: webmaster
        webmaster: root
        noc: root
        hostmaster: root
        info: postmaster
        sales: postmaster
        support: postmaster
        # trap decode to catch security attacks
        decode: root
        contact: "{{ ovirt_infra_ml_pv }}"
        # aliases that jira would use
        infra-support: jira
        community: "{{ ovirt_community_emails }}"
        ## Random new aliases we create
        wordpress: community
        twitter: community
        identica: community
        ovirtbot: "{{ eedri_mail }}"
        kerri: "{{ kerri_mail }}"
        pr: "{{ ovirt_press_emails }}"
        press: "{{ ovirt_press_emails }}"
        hootsuite: "{{ eedri_mail }}"
        quaid: "{{ quaid_mail }}"
        events: community
        ovirt-copr: "{{ eedri_mail }}"
        infra-twitter: infra-private
        privacy: infra-private
      use_simple_tls: True
      # social_auth is defined in host_vars
      # caught by underlying 'mailman3' role
      with_fedora_auth: True
      # caught by underlying 'postgrey' role
      whitelist_clients:
        - gerrit.ovirt.org
        - redhat.com
      # caught by underlying 'postfix' role
      myorigin: "{{ ovirt_domain }}"
      mynetworks:
        - 66.187.230.42
      local_accounts:
        - jira
        - jenkins
  - name: Install POP3 Server
    include_role:
      name: dovecot
    vars:
      with_pop3: true
      # inherit TLS settings from 'mailing-lists-server' role
      auth: yaml-dict
  - name: Configure web access to old ML archives
    copy:
      src: "mailing/web/old_ml_archives.conf"
      # Duck: we should think about making _vhost_confdir part of the public API
      dest: "{{ _vhost_confdir }}/"
      owner: root
      group: root
      mode: 0644
    notify: reload httpd
  - name: install Dovecot users
    copy:
      src: mailing/users/
      dest: /etc/dovecot/users/
  - name: Auto-expire Jenkins mailbox
    cron:
      name: "Auto-expire Jenkins mailbox"
      minute: "21"
      hour: "6"
      user: root
      job: "doveadm expunge -u jenkins mailbox Inbox savedbefore 30d"

- hosts: web_builders
  vars:
    website_username: web_builder
  roles:
  - role: builder
    builder_name: "{{ website_name }}"
    builder: "{{ website_builder | default('middleman') }}"
    builder_username: "{{ website_username }}"
    git_url: "{{ website_repo_url }}"
    git_version: master
    auto_deploy_hour: "*/6"
    cron_error_email: "{{ osas_builder_error_email }}"
  - role: msmtp
    smart_host: "{{ mail_forwarder }}"
    disable_freeipa: true
  tasks:
  - name: fetch dashboard
    cron:
      name: "fetch dashboard"
      minute: "0"
      hour: "*/6"
      user: "{{ website_username }}"
      job: "cd /srv/builder/{{ website_name }} && ./fetch-dashboard.rb"
    when: website_has_dashboard is defined and website_has_dashboard

- hosts: www.phx.ovirt.org
  tasks:
    - name: create web builder's user
      user:
        name: "{{ websync_user }}"
        comment: "Web Builder User"
    - name: "Create vhost for {{ inventory_hostname }}"
      include_role:
        name: httpd
        tasks_from: vhost
      vars:
        website_domain: www.ovirt.org
        server_aliases:
          - ovirt.org
        document_root: "{{ websync_path }}"
        document_root_group: "{{ websync_user }}"
        use_tls: True
        use_letsencrypt: True
        mail_domain: ovirt.org
        force_tls: True
        redirects:
          - src: /stats
            target: https://ovirt.biterg.io/

